syne_dataplatform:
    outputs:
      dev:
        dataset: syne_dataplatform_dev
        job_execution_timeout_seconds: 300
        job_retries: 1
        keyfile: /usr/local/airflow/dbt/syne_dataplatform/profiles_dir_docker/digital-sprite-404604-6a798dd8e70f.json
        location: US
        method: service-account
        priority: interactive
        project: digital-sprite-404604
        threads: 3
        type: bigquery
    target: dev