syne_dataplatform:
    outputs:
      dev:
        dataset: syne_dataplatform_dev
        job_execution_timeout_seconds: 300
        job_retries: 1
        keyfile: C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\syne_dataplatform\profiles_dir_local\digital-sprite-404604-6a798dd8e70f.json
        location: US
        method: service-account
        priority: interactive
        project: digital-sprite-404604
        threads: 3
        type: bigquery
        dataproc_region: us-central1
        gcs_bucket: dbt-spark-bucket
    target: dev