# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "first-job"

  first-job:

    # The type of runner that the job will run on. You can get list of runner from latest GitHub documents or google.
    #However, for this example we are using ubuntu-latest runner.

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo "Hello World!"

      # Runs a single command using the runners shell
      - name: Print goodbye
        run: echo "Done - bye!"