# This is a basic workflow to help you get started with Actions

name: First Workflow
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Environment'
        options:
          - non-prod
          - uat
          - prod
        required: true
      dag_name:
        description: 'DAG Name'
        default: ''
        required: false
      model_name:
        description: 'Model Name'
        default: ''
        required: false
      folder_name:
        description: 'Folder Name'
        default: ''
        required: true
      branch_name:
        description: 'Branch Name'
        default: ''
        required: true
      commit_message:
        description: 'Commit Message'
        default: ''
        required: true
jobs:
  deploy-nonprod:
    runs-on: ubuntu-latest
    if: github.event.input.env == 'non-prod'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #  persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.6'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install psycopg2
          # pip install -r docker/requirements.txt
          echo ${{github.event.input.dag_name}}
          echo ${{github.event.input.model_name}}
          echo ${{github.event.input.folder_name}}
      

