# This is a basic workflow to help you get started with Actions

name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      dag_name:
        description: 'DAG Name'
        default: ''
        required: false
      model_name:
        description: 'Model Name'
        default: ''
        required: false
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"

      - name: Print goodbye
        run: echo "Done - bye!"
